In [1]:
import numpy as np

# GAUSSIAN ELIMINATION 
# solving Ax = b by turning A into an upper triangle and then back-solving
def gauss(A, b):
    A = np.array(A, dtype=float)  # copy A so we don’t ruin the original
    b = np.array(b, dtype=float)  # same for b
    n = len(b)

    # make everything below the diagonal = 0
    for i in range(n):
        # pivoting: swap in the row with the biggest number 
        p = i + np.argmax(np.abs(A[i:, i]))
        A[[i, p]] = A[[p, i]]
        b[[i, p]] = b[[p, i]]

        # kill entries under the pivot
        for j in range(i + 1, n):
            m = A[j, i] / A[i, i]      # multiplier
            A[j, i:] -= m * A[i, i:]  # row operation on A
            b[j] -= m * b[i]          # do same thing to b

    # now solve from the bottom up (back substitution)
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        # solve for x_i once everything to the right is known
        x[i] = (b[i] - np.dot(A[i, i+1:], x[i+1:])) / A[i, i]

    return x


# LU DECOMPOSITION 
# split A into L (lower) and U (upper) so A = L @ U
def lu(A):
    A = np.array(A, dtype=float)  # don’t touch the original
    n = A.shape[0]

    L = np.eye(n)   # L starts as identity like 1s on diagonal
    U = A.copy()    # U starts as A and gets cleaned up

    for i in range(n):
        for j in range(i + 1, n):
            m = U[j, i] / U[i, i]   # same multiplier idea as Gaussian elim
            L[j, i] = m             # save multiplier in L
            U[j, i:] -= m * U[i, i:]# zero out below the pivot in U

    return L, U


A = [[3, 2, -4],
     [2, 3,  3],
     [5, -3, 1]]
b = [3, 15, 14]

print("Gaussian elimination solution:")
print(gauss(A, b))

A2 = [[2, 3,  1],
      [4, 7, -1],
      [-2, 1, 2]]

L, U = lu(A2)
print("\nL matrix:")
print(L)
print("U matrix:")
print(U)

Gaussian elimination solution:
[3. 1. 2.]

L matrix:
[[ 1.  0.  0.]
 [ 2.  1.  0.]
 [-1.  4.  1.]]
U matrix:
[[ 2.  3.  1.]
 [ 0.  1. -3.]
 [ 0.  0. 15.]]
